### ISSUE TITLE
Support for Authentication Type Connections

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/terraform-provider-davinci#10]
### Affected Resource(s)
- data connections
- data connection
- resource connection

### Terraform Configuration Files
```hcl
## Potential update
resource "davinci_connection" "foo" {

  name = "Foo"
  environment_id= "abc-123"
  connector_id = "genricConnector"

  ## new field only needed for authentication type connections. 
  ## max 1
  customauth_properties {
    provider_name = ""
    ...
  }
}
```

### Expected Behavior
This is the most common type of "complicated connector" it is used for generic oidc as well as any other oidc style connector. For example: Facebook login, Google login, LinkedIn, Early Warning.

**Comment by pingone-davinci** [comment]
Another connection resource that has this is Slack.  We've discussed, but just wanted to mention in issue.

**Comment by patrickcping** [comment]
Needs re-triage to understand if there are code changes needed

**Comment by samir-gandhi** [comment]
This is still valid. Haven't heard demand for it, but safe to assume demand is there as usage has grown.

**Comment by samir-gandhi** [comment]
Some of the bootstrapped connections may use this format as well as the bootstrapped flow. This enhancement would be needed if:
- someone wants to use those in a fresh, minimal DaVinci Environment
- we want to host a davinci bootstrap example

This item should now be prioritized

**Comment by samir-gandhi** [comment]
as this is built, we will also need to update the doc generator to support customAuth connectors

**Comment by patrickcping** [comment]
#279 raised to implement complex property types as a raw JSON format.  This will cover connectors such as the User Pool, OIDC, SAML and third party connectors that also take OIDC or OAuth2.0 style parameters.

This is intended as a medium-term resolution while the DaVinci management APIs are currently being re-designed
