### ISSUE TITLE
Unable to run flows with multiValue function - appears to not use orx on creation

### ISSUE THREAD

**Issue by tsigle** [pingidentity/terraform-provider-davinci#11]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
```
Terraform v1.2.9
on darwin_arm64
```

### Affected Resource(s)
Please list the resources as a list, for example:
- resource_flow

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
Any flow with a multiValue function

### Debug Output
n/a

### Panic Output
n/a

### Expected Behavior
Valid flow with a MultiValue Function that works

### Actual Behavior
The flow simply stops on the MultiValue Function

### Steps to Reproduce
Create a flow with a MultiValue Function

### Important Factoids
Appears to not evaluate the orx (orchestration field) from the flow when creating

### References
n/a

**Comment by samir-gandhi** [comment]
Was able to reproduce, found hidden orx call
