### ISSUE TITLE
After creating resource_application, when "try-flow", says policy not active

### ISSUE THREAD

**Issue by tsigle** [pingidentity/terraform-provider-davinci#12]
When creating a new application, immediately run "try-flow" from the application/policy.  Says the policy is not active.  If the policy is edited and simply saved with no changes, it runs fine.

**Comment by samir-gandhi** [comment]
related to #8

**Comment by samir-gandhi** [comment]
Able to reproduce, seems flow policy is not truly enabled. Working on this now

**Comment by samir-gandhi** [comment]
I see the issue. policies.status must be set to "enabled" so it gets sent in the creation of the flow policy. 
I'll updated the schema for this resource to default to enabled and update docs as well.
