### ISSUE TITLE
[ENHANCEMENT] davinci_variable to plugin framework

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/terraform-provider-davinci#120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Migrate davinci_variable datasources and resource to plugin framework

### New or Affected Resource(s)

- `davinci_variable`

**Comment by patrickcping** [comment]
Blocked until merge with PingOne provider

**Comment by patrickcping** [comment]
Moved to another project
