### ISSUE TITLE
[BUG] Constant error due to dependency suggestion in documentation

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-davinci#154]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### DaVinci Terraform provider Version

0.1.9

### Terraform Version

1.4.2

### Affected Resource(s)

- `davinci_connections`
- everything that `depends_on davinci_connections.read_all`

### Terraform Configuration Files
```hcl
data "pingone_user" "terraform" {
  environment_id = "davinci_admin_envid"
  username       = "terraform"
}

resource "pingone_role_assignment_user" "terraform_environment_admin" {
  environment_id       = "davinci_admin_envid"
  user_id              = data.pingone_user.terraform.id
  role_id              = data.pingone_role.environment_admin.id
  scope_environment_id = pingone_environment.dev.id
}

resource "pingone_role_assignment_user" "terraform_identity_data_admin" {
  environment_id       = "davinci_admin_envid"
  user_id              = data.pingone_user.terraform.id
  role_id              = data.pingone_role.identity_data_admin.id
  scope_environment_id = pingone_environment.dev.id
}

resource "pingone_role_assignment_user" "terraform_client_application_developer" {
  environment_id       = "davinci_admin_envid"
  user_id              = data.pingone_user.terraform.id
  role_id              = data.pingone_role.client_application_developer.id
  scope_environment_id = pingone_environment.dev.id
}

provider "davinci" {
  username       = "terraform"
  password       = "*********"
  environment_id = "davinci_admin_envid"
  region         = "AsiaPacific"
}

data "davinci_connections" "read_all" {
  environment_id = pingone_environment.dev.id
  depends_on = [
    pingone_role_assignment_user.terraform_environment_admin,
    pingone_role_assignment_user.terraform_identity_data_admin
  ]
}
```

### Expected Behavior

It should not throw errors

### Actual Behavior

On every single element, due to the `depends_on` calling for connections read_all, it throws
```
│ Error: For Connection 'PingOne MFA' and Property 'policyId': unable to identify value type, only string or boolean is currently supported
│ 
│   with data.davinci_connections.read_all,
│   on ./identity-service/output/dev.tf line 56, in data "davinci_connections" "read_all":
│   56: data "davinci_connections" "read_all" {
│ 
```

### Steps to Reproduce

1. follow https://registry.terraform.io/providers/pingidentity/davinci/latest/docs#full-deployment-example-with-a-pingone-environment
2. terraform plan (or apply)

**Comment by samir-gandhi** [comment]
Hi thanks for opening. 

I was not able to immediately reproduce the issue from the example in documentation. So could we have a couple of questions and maybe some clarifications.. 

Are you looking to manage an existing P1 environment, or are you creating the environment as part of this plan?

If the environment is created prior to this davinci provider work - i.e. not part of this plan, you don't need the `data.davinci_connections.read_all` nor the dependencies on it. That specific logic is intended to ensure any davinci resources wait for the environment to exist and for bootstrapping to complete. 

Also, if the environment is created prior to this davinci provider work, unless there are other unique errors, it seems like the core of this issue is around the davinci_connections datasource specifically trying to read the PingOne MFA connection. Is that resource being created as part of the plan or does it already exist in the environment?

If the environment is created as part of this plan, would you mind sharing service blocks included on the pingone_environment resource, and confirmation if you are licensed for each of them?

**Comment by dbryar** [comment]
This is an existing environment being taken over by Terraform.

In Ping One we are generating an import script ahead of the Terraform `plan`/`apply` from the existing setup using the Ping API, however that is not an option for DaVinci.

The Ping One MFA is correctly licensed and is already in use in DaVinci. The `policyId` in the existing connector is blank/undefined.

The documentation does not really make it clear the `depends_on` elements are there for a new environment only. As such I have removed them from the code and the error goes away.

Perhaps this is just a trigger to update the documentation, as linked?

**Comment by samir-gandhi** [comment]
I did test that an empty value for policyId on the PingOne MFA connector is fine. 

I agree that docs can be improved. There is a plan to document the full experience of bringing a davinci flow into hcl. I'll include these clarifications as part of that.

**Comment by samir-gandhi** [comment]
addressed new docs here: https://github.com/pingidentity/terraform-provider-davinci/pull/170/files#diff-2787aac6ad1510c9157d238b7b366aa4a6abdeba2429c28affad380e0bd3df26R25

**Comment by samir-gandhi** [comment]
@dbryar sorry I followed a red herring the first time around on this issue. I've now identified the actual [issue](#204) and can add some handling in for it.
