### ISSUE TITLE
`davinci_connection`: Unable to import the SMTP Client Connector due to port number

### ISSUE THREAD

**Issue by malenze** [pingidentity/terraform-provider-davinci#274]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### DaVinci Terraform provider Version
v0.2.1

### Terraform Version
v1.5.7

### Affected Resource(s)
- `davinci_connector`

### Terraform Configuration Files
```Shell
terraform import davinci_connection.smtpclient <environment_id>/<smtpconnector_id>
```
```hcl
data "davinci_connections" "read_all" {
environment_id = var.environment_id
}
```
```Shell
Planning failed. Terraform encountered an error while generating this plan.
│ Error: For Connection 'SMTP Client' and Property 'port': unable to identify value type, only string or boolean is currently supported
```

### Expected Behavior
- even if an SMTP Client Connector was configured manually, terraform provider should be able to read that connector either as a single connector or when trying to read all davinci connections.

### Actual Behavior
Error message, when trying to import or plan `terraform import` or `terraform plan`.

### Steps to Reproduce

1. Open the Davinci administration console
2. Add the `SMTP Client` connector in `Connectors`
3. Configure a port number, e. g. 25 or 465 are common and save the changes in the UI
4. add `data "davinci_connections" "read_all" { environment_id = var.environment_id }` to your `main.tf`file
5. `terraform plan`

### Important Factoids
- I am not sure, where this should be changed:
  1. the provider accepts type number
  2. the connector writes type string instead of number

### References
- couldn't find any

**Comment by samir-gandhi** [comment]
Hi @malenze thank you for opening this issue. 
I am able to reproduce and the issue is as you noted, a limitation of the accepted types for connection properties. 
We will include a fix in the 0.3.0 release or shortly after.
