### ISSUE TITLE
Upgrade from 0.2 to 0.3 shows all variables in flows being delete

### ISSUE THREAD

**Issue by dbryar** [pingidentity/terraform-provider-davinci#299]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### DaVinci Terraform provider Version

0.3.1

### Terraform Version

1.4.2

### Affected Resource(s)

- `davinci_flow`

### Terraform Configuration Files
CDK TF outputs cdk.tf.json, and this is an excerpt
```json
{
  "davinci_flow": {
    "change_email_magic_link": {
      "connection_link": [
        {
          "id": "${data.davinci_connection.variables.id}",
          "name": "Variables"
        },
        {
          "id": "${data.davinci_connection.flow_conductor.id}",
          "name": "Flow Conductor"
        },
        {
          "id": "${data.davinci_connection.challenge.id}",
          "name": "Challenge"
        },
        {
          "id": "${resource.davinci_connection.ping_one_notifications.id}",
          "name": "PingOne Notifications"
        },
        {
          "id": "${data.davinci_connection.http.id}",
          "name": "Http"
        },
        {
          "id": "${data.davinci_connection.teleport.id}",
          "name": "Teleport"
        }
      ],
      "deploy": true,
      "environment_id": "${pingone_environment.dev.id}",
      "flow_json": " ... ",
      "subflow_link": []
    }
  }
}
```

### Debug Output

```log
# davinci_flow.change_email_magic_link_ will be updated in-place
  ~ resource "davinci_flow" "change_email_magic_link_" {
      ~ description             = "Verify an email address change request using a magic link." -> (known after apply)
      ~ flow_configuration_json = (sensitive value)
      ~ flow_export_json        = (sensitive value)
      ~ flow_json               = (sensitive value)
      ~ flow_variables          = [
          - {
              - context = "company" -> null
              - id      = "baseUrl##SK##company" -> null
              - max     = 2000 -> null
              - min     = 0 -> null
              - name    = "baseUrl" -> null
              - type    = "property" -> null
            },
          - {
              - context = "company" -> null
              - id      = "clientId##SK##company" -> null
              - max     = 2000 -> null
              - min     = 0 -> null
              - name    = "clientId" -> null
              - type    = "property" -> null
            },
          - {
              - context = "company" -> null
              - id      = "clientSecret##SK##company" -> null
              - max     = 2000 -> null
              - min     = 0 -> null
              - mutable = true -> null
              - name    = "clientSecret" -> null
              - type    = "property" -> null
            },
          - {
              - context = "flow" -> null
              - flow_id = "97d99a3064c6eebf4bb4368dde5887dd" -> null
              - id      = "scope##SK##flow##SK##97d99a3064c6eebf4bb4368dde5887dd" -> null
              - max     = 2000 -> null
              - mutable = true -> null
              - name    = "scope" -> null
              - type    = "property" -> null
            },
        ] -> (known after apply)
        id                      = "97d99a3064c6eebf4bb4368dde5887dd"
        name                    = "Change Email (Magic Link)"
        # (2 unchanged attributes hidden)
        # (6 unchanged blocks hidden)
    }
```

This is consistent on every existing flow

### Steps to Reproduce

update to provider version 0.3.1
1. `terraform plan`

### Important Factoids

We have previously been avoiding updates to 0.x.0 branches due to having significant resources that are deployed. We would like to use the new mapping feature for subflows/connectors to avoid the missing node connectors, however the `plan` shows a significant number of delete requests.

Is this normal, and if so, should it be flagged as such somewhere? (I will also check release notes)

**Comment by patrickcping** [comment]
hi @dbryar, thanks for raising!

Let me look into this and get back to you.  If it is safe and normal, I'll create some documentation guidance

**Comment by dbryar** [comment]
Please advise update when available (if this is actually destructive) as we would like to export flows from upper envs back to lower envs and align all the connector/subflow IDs using the new replacement feature in 0.3.x

**Comment by patrickcping** [comment]
Just to confirm, this is not destructive.  To explain what is happening here:

`flow_variables` exists in the state file at version `v2.x`, this is actually a read-only field, it reads this configuration from the successful import.  We don't actually compute a forward plan for `flow_variables`, so it's always "Unknown" (known after apply) when the resource gets updated (for example, with an altered flow).

In this case, moving to `v3.x` Terraform has to mark the resource as "to be updated" (even if the flow JSON and other attributes are the same) because we need to populate the state file with new fields in the schema.  It will make a `PUT` API request with the same flow JSON, but it won't remove/re-create the resource and the variables are kept intact.  They'll then be populated in `flow_variables` after the flow has been updated successfully.

I'll leave this issue open because we should update the provider to create a forward plan for `flow_variables` based on the JSON import file, this would make things clearer when updating a flow.
