### ISSUE TITLE
`application_id` not necessary

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-davinci#36]
Where the resource is `davinci_application`, the `application_id` is not necessary as it will instead be used as the `id`

https://github.com/pingidentity/terraform-provider-davinci/blob/1a2d766c9ea4d46438d888b105b2157ca636f7d1/internal/service/davinci/resource_application.go#L26-L30

This may apply to other resources and datasources

**Comment by samir-gandhi** [comment]
Following P1. 
- when the field is `Required` **or** `Computed` and `Optional` keep it as `element_id` - I assume for UX. 
- when the field is `Computed` **only**  use `id. 

updating schema per this.
