### ISSUE TITLE
Documentation needed for all schema fields

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-davinci#38]
All schema fields we expose should have documentation attached.  Ideally these come from any official documentation we might have

https://github.com/pingidentity/terraform-provider-davinci/blob/1a2d766c9ea4d46438d888b105b2157ca636f7d1/internal/service/davinci/resource_application.go#L31-L34

Applies to all schema

**Comment by samir-gandhi** [comment]
resolved in
