### ISSUE TITLE
Naming of multi-value sets

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-davinci#42]
General preference might be that multi-value set/lists of embedded schema should use singular naming, e.g. `policy` due to the way it's written in HCL.
Example, where `policies` and `flows` might need to change to `policy` and `flow`:
```
resource "davinci_application" "use_default_flow" {
  name           = "PingOne SSO Connection"
  environment_id = var.pingone_environment_id
  oauth {
    enabled = true
    values {
      allowed_grants                = ["authorizationCode"]
      allowed_scopes                = ["openid", "profile"]
      enabled                       = true
      enforce_signed_request_openid = false
      redirect_uris                 = ["https://auth.pingone.com/0000-0000-000/rp/callback/openid_connect"]
    }
  }
  policy {
    name   = "PingOne - Sign On and Password Reset"
    status = "enabled"
    flow {
      id    = "abc123"
      version_id = -1
      weight     = 100
    }
  }
  saml {
    values {
      enabled                = false
      enforce_signed_request = false
    }
  }
}
```

Sets/lists of a single value should use the plural naming. e.g. `allowed_scopes` (as already configured in code)

https://github.com/pingidentity/terraform-provider-davinci/blob/1a2d766c9ea4d46438d888b105b2157ca636f7d1/examples/resources/davinci_application/resource.tf#L2-L30

**Comment by samir-gandhi** [comment]
okay so:
if TypeSet && !MaxItems:1 then Singular name.
This makes sense from a consumer perspective, rather than literal API mapping.

**Comment by samir-gandhi** [comment]
`connection` is a terraform internal keyword https://developer.hashicorp.com/terraform/language/resources/provisioners/connection#connection-block
using `connection_link` and `subflow_link` instead
