### ISSUE TITLE
Discussion: should the presence of the `oauth {}` or `saml {}` blocks imply `enabled = true`

### ISSUE THREAD

**Issue by patrickcping** [pingidentity/terraform-provider-davinci#43]
https://github.com/pingidentity/terraform-provider-davinci/blob/1a2d766c9ea4d46438d888b105b2157ca636f7d1/examples/resources/davinci_application/resource.tf#L6

The PingOne provider implicitly sets `enabled = true` flags based on the presence of the surrounding block.  This allows the general configuration to be flattened into a single structure, for example, it might look like the following where oauth is enabled and saml is not:
```hcl
resource "davinci_application" "use_default_flow" {
  name           = "PingOne SSO Connection"
  environment_id = var.pingone_environment_id
  oauth {
      allowed_grants                = ["authorizationCode"]
      allowed_scopes                = ["openid", "profile"]
      enabled                       = true
      enforce_signed_request_openid = false
      redirect_uris                 = ["https://auth.pingone.com/0000-0000-000/rp/callback/openid_connect"]
  }
  ...
}
```

This obviously deviates from the underlying API, but might be more user-friendly

**Comment by samir-gandhi** [comment]
Aiming for a better UX is always the answer.

**Comment by patrickcping** [comment]
Closing as no action, waiting for updated APIs
