### ISSUE TITLE
Go Client - Set Environment should check that target environment is accessible

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/terraform-provider-davinci#55]
### Expected Behavior
Set environment sets a _valid_ environment id for access_token

### Actual Behavior
Set environment _always_ returns 200 and thus allows actual DV api call to be sent regardless of if environment exists. If an api call is sent to a nonexistent environment and auth is re-initialized, it is possible that the api call will be sent to the default environment for the user. 

### Steps to Reproduce
TBD

**Comment by patrickcping** [comment]
Needs triage - should this be moved to https://github.com/samir-gandhi/davinci-client-go/issues

**Comment by samir-gandhi** [comment]
Closing as won't do, this is circumvented in the provider with the CheckAndRefreshAuth function and is something that should change on the backend API but should be covered by new DV APIs.
