### ISSUE TITLE
[ENHANCEMENT] Support takeover of existing/bootstrapped resources

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/terraform-provider-davinci#66]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Newly created Davinci environments have bootstrapped resources. Naturally these are 'unmanaged' in terraform. Having a mix of 'managed' and 'unmanaged' resources in an environment can easily lead to confusion or worse. Additionally, there are many cases in which customers would want to create and configure a DaVinci environment in the same step, this is challenging 

### New or Affected Resource(s)

- davinci_*

### Potential Terraform Configuration

```hcl
resource "davinci_connection" default_http {
  //new field, all others are required
  update_or_create = true
  name  = http
}

resource "davinci_flow" "default_pingone_sso" {
  //new field, all others are required
  update_or_create = true
  name = "PingOne SSO"
  flow_json = "<pingone_sso_flow_json>"
  deploy = true
}
```

### References

* #0000

**Comment by patrickcping** [comment]
This work should pause while P14C-43494 is evaluated.  The ideal situation is that the provider can work in a clean environment, where we don't incur code complexity/technical debt on implied configuration

**Comment by dbryar** [comment]
Trying to configure the Ping One MFA or Ping One Notifications (in both cases, adding policy IDs) via Terraform creates a new connector with a blank Client Secret

```hcl
resource "davinci_connection" "ping_one_mfa" {
  environment_id = pingone_environment.dev.id
  connector_id   = "pingOneMfaConnector"
  name           = "PingOne MFA"
  property {
    name  = "region"
    value = "AP"          ## this is inconsistent with all other use of region values
  }
  property {
    name  = "envId"
    value = pingone_environment.dev.id
  }
  property {
    name  = "clientId"
    value = tolist(data.davinci_connection.ping_one.property)[index(tolist(data.davinci_connection.ping_one.property).*.name, "clientId")].value
  }
  property {
    name  = "clientSecret"
    value = tolist(data.davinci_connection.ping_one.property)[index(tolist(data.davinci_connection.ping_one.property).*.name, "clientSecret")].value
  }
  property {
    name  = "policyId"
    value = pingone_mfa_policy.mfa_policy.id
  }
}
```

`plan` or `apply` output is as follows
```
  # davinci_connection.ping_one_mfa will be created
  + resource "davinci_connection" "ping_one_mfa" {
      + connector_id   = "pingOneMfaConnector"
      + created_date   = (known after apply)
      + customer_id    = (known after apply)
      + environment_id = "cf4xxxxxxxxxxxxec"
      + id             = (known after apply)
      + name           = "PingOne MFA"
      + property {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + property {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + property {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + property {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
      + property {
          # At least one attribute in this block is (or was) sensitive,
          # so its contents will not be displayed.
        }
    }
```

**Comment by patrickcping** [comment]
"Empty" or "clean" DaVinci environments can now be created, so overwriting existing resources is no longer required/recommended

### By API

The follow API example shows how an environment can be created without bootstrapped/demo configuration, notice the `billOfMaterials.products.tags` array attribute:

```
curl --location 'https://api.pingone.eu/v1/environments' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer <<token>>' \
--data '{
  "name": "New-Env_1698254427",
  "description": "New environment description",
  "type": "SANDBOX",
  "region": "EU",
  "billOfMaterials": {
    "products": [
      {
        "type": "PING_ONE_BASE",
        "description": "New environment product description",
        "console": {
          "href": "https://example.com"
        }
      },
      {
        "type": "PING_ONE_DAVINCI",
        "description": "New environment product description",
        "tags": ["DAVINCI_MINIMAL"]
      }
    ]
  },
  "license": {
    "id": "********-****-****-****-*************"
  }
}'
```

### By PingOne Terraform Provider

This functionality will be delivered in `v0.23.0` of the provider on completion of https://github.com/pingidentity/terraform-provider-pingone/issues/611

**Comment by patrickcping** [comment]
Needs re-triage to determine if there are any configuration items that need to be taken over now DaVinci environments can be created "clean".  If no configuration items need taking over in a clean environment, this issue can be closed as "no action"

**Comment by samir-gandhi** [comment]
Agreed, now that we can support empty environments this is no longer needed. 
We will continue maintain testing for bootstrapped resources per the deprecation strategy (i.e. until 1.0.0 or merge with pingone provider)
